spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawler?useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  
  jpa:
    show-sql: true
    database: mysql
    
   
